### PR TITLE
Define primary and secondary colors as css variables.

### LINKED ISSUE #56: Extract out color and header pt-weight styling to the global stylesheet
Extract the font sizing and weights along with colors

DoD:
- The font sizing is applied to h1, h2, h3, h4, h5, and body
- The font weight is bold for h1, h2, h3
- The font weight is semibold for h4
- The font weight is regular for h5
- The Primary, Primary Light, Primary Dark, Secondary Light, Secondary Dark colors are available through CSS variables

Note: These are all defined in the Figma document in the wiki

### PR DESCRIPTION
**Pull request by ThatMarko**
Define header pt and weight styling and body font size.
Define primary and secondary colors as CSS variables for use with  ``` rgb(a b c / <alpha-value>); ```
Fixes #56

### CODE REVIEW

**Review by ChristianBingman — CHANGES_REQUESTED** [review]
It looks great and works well. Thank you for also adding the tailwind colors as well. The only thing I have to ask is that the color names in Tailwind colors are kept consistent with how class naming is done. E.g. instead of primaryDark, use primary-dark. Thanks again!

**Comment by ChristianBingman** [comment]
Also, why are you using RGB values instead of hex color codes? If no reason in particular, hex color codes are more common and I would recommend using those

**Comment by ThatMarko** [comment]
I looked at available documentation of [theme color object syntax](https://tailwindcss.com/docs/customizing-colors#color-object-syntax) and found out how to do the "-" instead of the camel case, see new changes.

Regarding the using CSS variables to define colors, according to the [using CSS variables documentation](https://tailwindcss.com/docs/customizing-colors#using-css-variables) they said that the recommended way is to define the variables as channels otherwise the [opacity modifiers](https://tailwindcss.com/docs/opacity#changing-an-element-s-opacity) won't work.

I never had an opportunity to play around with Tailwind so I'm following the documentation recommendations. There's also a [plugin for adding base styles](https://tailwindcss.com/docs/plugins#adding-base-styles) which I could try to use to implement the requested styling for the headers. Let me know otherwise feel free to merge.

**Comment by ChristianBingman** [comment]
Ah I see, I wasn't aware of that. Thanks! LGTM

**Review by ChristianBingman — APPROVED** [review]
Looks great!

**Pull request merged**
