### PR TITLE
Fixes #71

### LINKED ISSUE #71: Open maps on "Show on Map"
When the user clicks show on map, it should open it in either their system maps application, or google maps

DoD:
- When the user clicks the button, open a location in maps
- It should open in a new tab/application

Note: This will require some research, maybe even a custom library that handles this

### PR DESCRIPTION
**Pull request by emoral435**
Added a ShowOnMap component that accepts the locations coordinates as a prop. It opens a new window as a popup, and works on mobile. Also fixed PrimaryButton, as it needed to have proptypes enabled on it so that no future errors would occur.

### CODE REVIEW

**Review by ChristianBingman — CHANGES_REQUESTED** [review]
A few small changes, ignore the eslint errors for now.

**Comment by ChristianBingman** [comment]
Actually if you just don't change anything about the primary button and remove the ShowMap prop type stuff you will be good to go

**Comment by emoral435** [comment]
I think it should work now, and I made the opening link more intuitive for us to add later on

**Review by ChristianBingman — APPROVED** [review]
Looks good to me, not sure if this is something we wan't to be handled in a generic js file, but for now it is fine.

**Pull request merged**
