### PR TITLE
Fixes #54

### LINKED ISSUE #54: Add mobile styling for Who We Are section
Update the styling of the who are we section on mobile

DoD:
- The mobile version removing the extra margin/padding on the body
- The header and body are properly centered
- The font styling stays the same

### PR DESCRIPTION
**Pull request by emoral435**
Added breakpoints for small screens so mobile has centered Who Are We. If the breakpoints are set at an incorrect position, let me know whether I should change it to md, lg, or if I should create a new breakpoint in the tailwind config file. Thanks!

### CODE REVIEW

**Review by ChristianBingman — CHANGES_REQUESTED** [review]
Could you add a little more padding around the body text on small screens? Thanks!

**Comment by ChristianBingman** [comment]
Could you only do it on small screens and keep it horizontally padded?

**Comment by emoral435** [comment]
My bad for not putting the sm breakpoint, I did not notice that, thank you!

**Review by ChristianBingman — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
