### PR TITLE
Fixes issue #57

### PR DESCRIPTION
**Pull request by emoral435**
Added Primary Button and Primary Button (hovering)

### CODE REVIEW

**Review by ChristianBingman — CHANGES_REQUESTED** [review]
You submitted an empty index.js file.

**Comment by emoral435** [comment]
Alright, the file somehow didn't get committed but I think the issue should be solved now.

**Review by ChristianBingman — CHANGES_REQUESTED** [review]
It is extremely close, I think the my should be 2 and mx should be 6 to keep it close to the original design. This should be the last change!

**Comment by emoral435** [comment]
I changed the padding accordingly, unless you meant to add margins as well, in which I can!

**Review by ChristianBingman — APPROVED** [review]
Looks great! Thank you for working with me on the changes!

**Pull request merged**
